# Generated by Django 4.2.2 on 2023-09-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nam',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='pic',
        ),
    ]
